import { describe, expect, test } from "bun:test";

describe("shared component styles", () => {
  test("documents baseline selectors for public component variants", async () => {
    const css = await Bun.file(new URL("./styles.css", import.meta.url)).text();

    expect(css).toContain(".app-shell");
    expect(css).toContain("@media (max-width: 48rem)");
    expect(css).toContain(".accordion-item summary");
    expect(css).toContain(".accordion-item summary span");
    expect(css).toContain(".aspect-ratio");
    expect(css).toContain(".avatar");
    expect(css).toContain(".breadcrumbs ol");
    expect(css).toContain('.button[data-variant="ghost"]');
    expect(css).toContain(".button-group");
    expect(css).toContain(".callout");
    expect(css).toContain(".choice-field");
    expect(css).toContain(".dialog");
    expect(css).toContain("dialog.dialog:not([open])");
    expect(css).toContain("background: var(--hd-surface-bg)");
    expect(css).toContain("color: var(--text, CanvasText)");
    expect(css).toContain(".code-token--keyword");
    expect(css).toContain(':where(html[data-theme="dark"], [data-theme="dark"]) .code-block');
    expect(css).toContain(".empty-state");
    expect(css).toContain(".icon-button");
    expect(css).toContain(".kbd");
    expect(css).toContain(".metadata-list");
    expect(css).toContain(".notification-banner");
    expect(css).toContain('.notification-banner[data-severity="danger"]');
    expect(css).toContain(".pagination");
    expect(css).toContain(".page-header-content");
    expect(css).toContain(".page-header h1");
    expect(css).toContain("font-size: var(--font-size-4, 2rem)");
    expect(css).toContain(".radio-group");
    expect(css).toContain("gap: 0.45rem");
    expect(css).toContain(".radio-group label");
    expect(css).toContain("grid-template-columns: auto minmax(0, 1fr)");
    expect(css).toContain('.radio-group input[type="radio"]');
    expect(css).toContain("appearance: none");
    expect(css).toContain("viewBox=%220%200%2020%2020%22");
    expect(css).toContain("width: 100%");
    expect(css).toContain("anchor-name: var(--popover-anchor-name)");
    expect(css).toContain("position-anchor: var(--popover-anchor-name)");
    expect(css).toContain(".popover-menu-panel:popover-open");
    expect(css).toContain("@supports not (position-anchor: --popover-anchor-name)");
    expect(css).toContain("inset-block-start: calc(100% + 0.35rem)");
    expect(css).toContain(".popover-menu-form");
    expect(css).toContain(".popover-menu-item:hover");
    expect(css).toContain(".basic-graph-axis");
    expect(css).toContain(".basic-graph-label");
    expect(css).toContain(".basic-graph-value");
    expect(css).toContain(".prose");
    expect(css).toContain(".separator");
    expect(css).toContain(".side-nav ul");
    expect(css).toContain(".skeleton");
    expect(css).toContain(".staged-form");
    expect(css).toContain('.staged-form-step [aria-disabled="true"]');
    expect(css).toContain(".stat-block");
    expect(css).toContain('.status-symbol[data-shape="triangle"]');
    expect(css).toContain(".table-filter-summary");
    expect(css).toContain(".scrollable-table-container");
    expect(css).toContain(".scrollable-table th[aria-sort]");
    expect(css).toContain(".scrollable-table th a");
    expect(css).toContain(".timeline-list");
    expect(css).toContain(".tooltip");
    expect(css).toContain(".validation-summary");
    expect(css).toContain(".button:disabled");
    expect(css).toContain(".compact-list-row dd");
    expect(css).toContain('.switch[data-variant="compact"] .switch-track');
    expect(css).not.toContain("Walking Pace");
    expect(css).not.toContain("Character Sheet");
  });
});
