export const sharedStoryCoverage = {
  Accordion: "Components/Shared/App Builder Reuse",
  AppShell: "Components/Shared/Second Wave Primitives",
  Badge: "Components/Shared/Existing Primitives",
  Breadcrumbs: "Components/Shared/Second Wave Primitives",
  Button: "Components/Shared/Core Primitives",
  ButtonGroup: "Components/Shared/Core Primitives",
  Callout: "Components/Shared/Second Wave Primitives",
  Card: "Components/Shared/Atoms/Card",
  CheckboxField: "Components/Shared/Core Primitives",
  Chip: "Components/Shared/Atoms/Chip",
  CodeBlock: "Components/Shared/Second Wave Primitives",
  CompactList: "Components/Shared/App Builder Reuse",
  Dialog: "Components/Shared/Second Wave Primitives",
  EmptyState: "Components/Shared/Second Wave Primitives",
  Fieldset: "Components/Shared/Core Primitives",
  FormField: "Components/Shared/Molecules/FormField",
  HxForm: "Components/Shared/Molecules/HxForm",
  Icon: "Components/Shared/Core Primitives",
  IconButton: "Components/Shared/Core Primitives",
  InputGroup: "Components/Shared/Molecules/InputGroup",
  LabelledOutput: "Components/Shared/Molecules/LabelledOutput",
  LinkButton: "Components/Shared/Core Primitives",
  LoadingIndicator: "Components/Shared/Second Wave Primitives",
  MetadataList: "Components/Shared/Second Wave Primitives",
  Notice: "Components/Shared/Second Wave Primitives",
  PageHeader: "Components/Shared/Second Wave Primitives",
  Pagination: "Components/Shared/Second Wave Primitives",
  Panel: "Components/Shared/Existing Primitives",
  PopoverMenu: "Components/Shared/App Builder Reuse",
  Progress: "Components/Shared/Second Wave Primitives",
  Prose: "Components/Shared/Second Wave Primitives",
  RadioGroup: "Components/Shared/Core Primitives",
  ScrollableTable: "Components/Shared/Molecules/ScrollableTable",
  SectionHeader: "Components/Shared/Second Wave Primitives",
  SegmentedControl: "Components/Shared/Core Primitives",
  SelectField: "Components/Shared/Core Primitives",
  SideNav: "Components/Shared/Second Wave Primitives",
  StatBlock: "Components/Shared/Second Wave Primitives",
  StatusSummary: "Components/Shared/Second Wave Primitives",
  Switch: "Components/Shared/Atoms/Switch",
  TableCell: "Components/Shared/Atoms/TableCell",
  Tabs: "Components/Shared/Second Wave Primitives",
  TextareaField: "Components/Shared/Core Primitives",
  TimelineList: "Components/Shared/Second Wave Primitives",
  Toolbar: "Components/Shared/Second Wave Primitives",
  ValidationSummary: "Components/Shared/Core Primitives",
} as const;

export const sharedIconStoryNames = [
  "add",
  "book",
  "calendar",
  "check",
  "close",
  "database",
  "delete",
  "dice",
  "document",
  "download",
  "edit",
  "external-link",
  "filter",
  "folder",
  "home",
  "lock",
  "map",
  "menu",
  "moon",
  "save",
  "search",
  "settings",
  "shield",
  "sparkles",
  "star",
  "sun",
  "tag",
  "upload",
  "user",
  "warning",
] as const;
