export interface HtmxProps {
  "hx-boost"?: string;
  "hx-confirm"?: string;
  "hx-delete"?: string;
  "hx-disable"?: string;
  "hx-disabled-elt"?: string;
  "hx-disinherit"?: string;
  "hx-encoding"?: string;
  "hx-ext"?: string;
  "hx-get"?: string;
  "hx-headers"?: string;
  "hx-history"?: string;
  "hx-history-elt"?: string;
  "hx-include"?: string;
  "hx-indicator"?: string;
  "hx-inherit"?: string;
  "hx-on"?: string;
  "hx-on--after-request"?: string;
  "hx-params"?: string;
  "hx-patch"?: string;
  "hx-post"?: string;
  "hx-preserve"?: string;
  "hx-prompt"?: string;
  "hx-push-url"?: string;
  "hx-put"?: string;
  "hx-replace-url"?: string;
  "hx-request"?: string;
  "hx-select"?: string;
  "hx-select-oob"?: string;
  "hx-swap"?: string;
  "hx-swap-oob"?: string;
  "hx-sync"?: string;
  "hx-target"?: string;
  "hx-trigger"?: string;
  "hx-validate"?: string;
  "hx-vals"?: string;
  "hx-vars"?: string;
}

export function htmxAttributes(props: HtmxProps) {
  return {
    "hx-boost": props["hx-boost"],
    "hx-confirm": props["hx-confirm"],
    "hx-delete": props["hx-delete"],
    "hx-disable": props["hx-disable"],
    "hx-disabled-elt": props["hx-disabled-elt"],
    "hx-disinherit": props["hx-disinherit"],
    "hx-encoding": props["hx-encoding"],
    "hx-ext": props["hx-ext"],
    "hx-get": props["hx-get"],
    "hx-headers": props["hx-headers"],
    "hx-history": props["hx-history"],
    "hx-history-elt": props["hx-history-elt"],
    "hx-include": props["hx-include"],
    "hx-indicator": props["hx-indicator"],
    "hx-inherit": props["hx-inherit"],
    "hx-on": props["hx-on"],
    "hx-on--after-request": props["hx-on--after-request"],
    "hx-params": props["hx-params"],
    "hx-patch": props["hx-patch"],
    "hx-post": props["hx-post"],
    "hx-preserve": props["hx-preserve"],
    "hx-prompt": props["hx-prompt"],
    "hx-push-url": props["hx-push-url"],
    "hx-put": props["hx-put"],
    "hx-replace-url": props["hx-replace-url"],
    "hx-request": props["hx-request"],
    "hx-select": props["hx-select"],
    "hx-select-oob": props["hx-select-oob"],
    "hx-swap": props["hx-swap"],
    "hx-swap-oob": props["hx-swap-oob"],
    "hx-sync": props["hx-sync"],
    "hx-target": props["hx-target"],
    "hx-trigger": props["hx-trigger"],
    "hx-validate": props["hx-validate"],
    "hx-vals": props["hx-vals"],
    "hx-vars": props["hx-vars"],
  };
}
